version = 0.1
[default.deploy.parameters]
stack_name = "trivia-app"
resolve_s3 = true
s3_prefix = "trivia-app"
region = "us-west-2"
profile = "281750582201"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
